export const DEFAULT_TACTIQ_ENDPOINT = 'https://tactiq-apps-prod.tactiq.io/transcript';

export const LANGUAGE_DISPLAY_NAMES: Record<string, string> = {
  en: 'English',
  zh: 'Chinese (Simplified)',
  'zh-CN': 'Chinese (Simplified)',
  'zh-TW': 'Chinese (Traditional)',
  es: 'Spanish',
  fr: 'French',
  de: 'German',
  ja: 'Japanese',
  ko: 'Korean',
  pt: 'Portuguese',
  ru: 'Russian',
  ar: 'Arabic',
  hi: 'Hindi',
  it: 'Italian',
  nl: 'Dutch',
  pl: 'Polish',
  tr: 'Turkish',
  th: 'Thai',
  vi: 'Vietnamese',
  id: 'Indonesian',
  ms: 'Malay',
  sv: 'Swedish',
  da: 'Danish',
  no: 'Norwegian',
  fi: 'Finnish',
  he: 'Hebrew',
  uk: 'Ukrainian',
  cs: 'Czech',
  hu: 'Hungarian',
  ro: 'Romanian',
  bg: 'Bulgarian',
  hr: 'Croatian',
  sk: 'Slovak',
  sl: 'Slovenian',
  et: 'Estonian',
  lv: 'Latvian',
  lt: 'Lithuanian'
};

export const DEFAULT_LANGUAGE_PROBE_ORDER = [
  'en',
  'es',
  'fr',
  'de',
  'ja',
  'ko',
  'zh',
  'pt',
  'ru',
  'ar',
  'hi'
];
